/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pendaftaran;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.awt.Dimension;
import java.awt.*;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author ASUS
 */
public class form extends javax.swing.JFrame {
    String nama,TTL,jurusan,fakultas,bidang;
    String nim;
    
    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getTTL() {
        return TTL;
    }

    public void setTTL(String TTL) {
        this.TTL = TTL;
    }

    public String getJurusan() {
        return jurusan;
    }

    public void setJurusan(String jurusan) {
        this.jurusan = jurusan;
    }


    public String getBidang() {
        return bidang;
    }

    public void setBidang(String bidang) {
        this.bidang = bidang;
    }

    public String getNim() {
        return nim;
    }

    public void setNim(String nim) {
        this.nim = nim;
    }
    
    
    
    
    void tampilTengah(){
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }
    
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        tampilTengah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fjurusan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbidang = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        fnim = new javax.swing.JTextField();
        fTTL = new javax.swing.JTextField();
        fakul = new javax.swing.JComboBox<>();
        jProgamming = new javax.swing.JCheckBox();
        jIOT = new javax.swing.JCheckBox();
        jMultimedia = new javax.swing.JCheckBox();
        jNetworking = new javax.swing.JCheckBox();
        jEduTech = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        nCetak = new javax.swing.JButton();
        nTambah = new javax.swing.JButton();
        nQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("TTL");

        fjurusan.setText("Jurusan");

        jbidang.setText("Bidang");

        fakul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "TEKKOM", "KESMAS", "MESIN", "KAPAL" }));
        fakul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakulActionPerformed(evt);
            }
        });

        buttonGroup1.add(jProgamming);
        jProgamming.setText("Progamming");

        buttonGroup1.add(jIOT);
        jIOT.setText("IOT");
        jIOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIOTActionPerformed(evt);
            }
        });

        buttonGroup1.add(jMultimedia);
        jMultimedia.setText("Multimedia");

        buttonGroup1.add(jNetworking);
        jNetworking.setText("Networking");

        buttonGroup1.add(jEduTech);
        jEduTech.setText("EduTech");

        jLabel7.setText("Form Pendaftaran");

        nCetak.setText("Cetak");
        nCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCetakActionPerformed(evt);
            }
        });

        nTambah.setText("Tambah");
        nTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTambahActionPerformed(evt);
            }
        });

        nQuit.setText("Quit");
        nQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nQuitActionPerformed(evt);
            }
        });

        keluar.setColumns(20);
        keluar.setRows(5);
        jScrollPane1.setViewportView(keluar);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fjurusan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbidang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fnama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fnim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fTTL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fakul, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jProgamming, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jIOT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jMultimedia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jNetworking, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jEduTech, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nCetak, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nTambah, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nQuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(177, 177, 177))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbidang)
                            .addComponent(jLabel5)
                            .addComponent(fjurusan)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jProgamming)
                                .addGap(18, 18, 18)
                                .addComponent(jIOT)
                                .addGap(18, 18, 18)
                                .addComponent(jMultimedia))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fTTL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fnim, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fakul, javax.swing.GroupLayout.Alignment.LEADING, 0, 157, Short.MAX_VALUE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jNetworking))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(nTambah)
                                        .addGap(48, 48, 48)
                                        .addComponent(nCetak)))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(nQuit))
                                    .addComponent(jEduTech)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fjurusan)
                    .addComponent(fakul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidang)
                    .addComponent(jProgamming)
                    .addComponent(jIOT)
                    .addComponent(jMultimedia))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNetworking)
                    .addComponent(jEduTech))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nCetak)
                    .addComponent(nQuit)
                    .addComponent(nTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCetakActionPerformed
        // TODO add your handling code here:
         
         //membuat objek dari class form
         form objFrom = new form ();
         objFrom.setNama(fnama.getText());
       objFrom.setNim(fnim.getText());
       objFrom.setTTL(fTTL.getText());
       objFrom.setJurusan(fakul.getSelectedItem().toString());
        // bidang
        StringBuffer bid = new StringBuffer ();
        if (jProgamming.isSelected()){
            bid.append(jProgamming.getText());
        }else if (jIOT.isSelected()){
            bid.append(jIOT.getText());
        }else if (jMultimedia.isSelected()){
            bid.append(jMultimedia.getText());
             }else if (jNetworking.isSelected()){
            bid.append(jNetworking.getText());
             }else if (jEduTech.isSelected()){
            bid.append(jEduTech.getText());
             }
        objFrom.setBidang(bid.toString());
        
        //keluar
        keluar.setText(
                "Nama/t : " + objFrom.getNama() +
                "\nNIM\t : " + objFrom.getNim() +
                "\nTTL\t : " + objFrom.getTTL() +
                "\nJurusan\t : " + objFrom.getJurusan() +
                        "\nBidang\t : " + objFrom.getBidang()
                        );
    }//GEN-LAST:event_nCetakActionPerformed

    private void jIOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIOTActionPerformed

    private void fakulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakulActionPerformed

    private void nTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTambahActionPerformed
        // TODO add your handling code here:
        nama = "";
        String nim = "";
        fakultas = "";
        bidang = "";
        TTL = "";
        fnama.setText("");
        fnim.setText("");
        fakul.setSelectedIndex(0);
        fTTL.setText("");
        
        if (jProgamming.isSelected ()){
            jProgamming.setSelected(false);
        }else
        if (jIOT.isSelected ()){
            jIOT.setSelected(false);
        }else
        if (jMultimedia.isSelected ()){
            jMultimedia.setSelected(false);
        }else
        if (jNetworking.isSelected ()){
            jNetworking.setSelected(false);
        }else
        if (jEduTech.isSelected ()){
            jEduTech.setSelected(false);
        }
    }//GEN-LAST:event_nTambahActionPerformed

    private void nQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nQuitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_nQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fTTL;
    private javax.swing.JComboBox<String> fakul;
    private javax.swing.JLabel fjurusan;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fnim;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JCheckBox jEduTech;
    private javax.swing.JCheckBox jIOT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox jMultimedia;
    private javax.swing.JCheckBox jNetworking;
    private javax.swing.JCheckBox jProgamming;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbidang;
    private javax.swing.JTextArea keluar;
    private javax.swing.JButton nCetak;
    private javax.swing.JButton nQuit;
    private javax.swing.JButton nTambah;
    // End of variables declaration//GEN-END:variables
}
